name: petshop_flutter
description: A Flutter app to manage pet records from a Spring Boot API.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner_pets.png
